# Generated by Django 4.2.16 on 2024-11-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
